version: 2

sources:
  - name: analytics
    schema: "{{ target.schema }}"
    tables:
      - name: iris_dataset
        description: "The Iris flower dataset"
        columns:
          - name: sepal_length
            description: "Sepal length in cm"
          - name: sepal_width
            description: "Sepal width in cm"
          - name: petal_length
            description: "Petal length in cm"
          - name: petal_width
            description: "Petal width in cm"
          - name: species
            description: "Species of Iris flower"