name: 'homework'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'homework'

# These directories tell dbt where to find things.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  homework:
    staging:
      +materialized: view
    mart:
      +materialized: table

seeds:
  homework:
    iris_dataset:
      +column_types:
        sepal_length: float
        sepal_width: float
        petal_length: float
        petal_width: float
        species: varchar